// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/editor" | "/game/[id]"
type AppRouteHandlerRoutes = "/api/editor/docs" | "/api/editor/games" | "/api/editor/list-files" | "/api/editor/list-tsx" | "/api/editor/load" | "/api/editor/save" | "/api/editor/save-styles" | "/api/editor/upload"
type PageRoutes = never
type LayoutRoutes = "/" | "/editor"
type RedirectRoutes = never
type RewriteRoutes = "/__nextjs_original-stack-frames" | "/_next/static/[[...path]]" | "/assets/[[...path]]" | "/game/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/__nextjs_original-stack-frames": {}
  "/_next/static/[[...path]]": { "path"?: string[]; }
  "/api/editor/docs": {}
  "/api/editor/games": {}
  "/api/editor/list-files": {}
  "/api/editor/list-tsx": {}
  "/api/editor/load": {}
  "/api/editor/save": {}
  "/api/editor/save-styles": {}
  "/api/editor/upload": {}
  "/assets/[[...path]]": { "path"?: string[]; }
  "/editor": {}
  "/game/[[...path]]": { "path"?: string[]; }
  "/game/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/editor": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
